### ISSUE TITLE
The spec example getting shares for google.com is volatile

### ISSUE THREAD

**Issue by stof** [dunglas/php-socialshare#12]
This is passing locally, but it fails on Travis for recent builds, receiving 12 rather than a number bigger than 1000

**Comment by stof** [comment]
Refs #8

**Comment by dunglas** [comment]
Yes it's a old known bug. Google probably applies some magic for IPs of large cloud providers.

A solution would be mock the response from Google but the main interest of this library is to get data from external services. If the remote format change and we use a mock we will never be notified.
